### ISSUE TITLE
{commit} variable not correctly set

### ISSUE THREAD

**Issue by pprazzi** [nishio-dens/bitbucket-pullrequest-builder-plugin#125]
I got these weird  '003db7d24cf9^{commit}' variabels that make my builds fail.

I have no idea where they might come from.

version 1.4.25

 > git fetch --tags --progress https://**removed**@bitbucket.org/**removed**/**removed**.git +refs/heads/*:refs/remotes/central/*
 > git rev-parse 003db7d24cf9^{commit} # timeout=10
FATAL: Command "git rev-parse 003db7d24cf9^{commit}" returned status code 128:
stdout: 003db7d24cf9^{commit}

stderr: fatal: ambiguous argument '003db7d24cf9^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

hudson.plugins.git.GitException: Command "git rev-parse 003db7d24cf9^{commit}" returned status code 128:
stdout: 003db7d24cf9^{commit}

stderr: fatal: ambiguous argument '003db7d24cf9^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1903)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1871)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1867)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1512)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1524)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:718)
	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
	at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:98)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:991)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1108)
	at hudson.scm.SCM.checkout(SCM.java:496)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1281)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Finished: FAILURE

**Comment by Snellingen** [comment]
I experience the same issue, is there any updated on this?

**Comment by CodeMonk** [comment]
Try typing that line by hand -- it works for me!

`codemonkey@MonkeyTree  ~/W/E/s/baristabot> git rev-parse '89faca1e3512^{commit}' # timeout=10
89faca1e3512604f47b655f0f25b26b9b7fff006
`
I'm not sure what you're hitting, but, that certainly looks like something in the git plugin, not the pr builder.

**Comment by CodeMonk** [comment]
@Snellingen Can you please reproduce and attach new logs - this shouldn't be happening.

Also, would you be able to try it with the tip of this repo? It hasn't been released, so you'll have to `mvn package` it to test.

**Comment by CodeMonk** [comment]
The second time it runs it's likely on the node - is your node running a different operating system than your master? What OS?

**Comment by CodeMonk** [comment]
Also, this failure has zero to do with the bitbucket-pullrequest-plugin, and is more likely due to a git misconfiguration in your jenkins environment.

**Comment by drew222** [comment]
The "Global Pipeline Libraries" are fetched before the pipeline runs on the worker. It seems to be failing on the master and the worker if a gitscm checkout is used in the pipeline with the same error.

**Comment by CodeMonk** [comment]
Actually, I just looked at my build. Looks like `checkout scm` does NOT work on a PR requested build. I use this instead:

      git branch: "${env.sourceBranch}", credentialsId: '****', url: 'git@bitbucket.org:ACCOUNT/REPO'

Could you see if something similar will work for you?

**Comment by drew222** [comment]
I tried replacing my 
`checkout scm` 
and my
`checkout( [
          $class: 'GitSCM',
          branches: [[name: '*/master']],
          doGenerateSubmoduleConfigurations: false,
          extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: "path"]],
          submoduleCfg: [],
          userRemoteConfigs: [[credentialsId: '****',
          url: 'git@bitbucket.org:user/project.git']]
          ]
        )`

with the git branch syntax that you suggested. Unfortunately it still fails on the pull for the second repo.

**Comment by CodeMonk** [comment]
I have never reproduced this failure myself, so, I'm kinda trying to help in the blind here.

Did something change to make this start happening for you? Or, has it been happening since 2017?

**Comment by drew222** [comment]
We've only just started using the plugin now. It seems like the way I'm able to consistently reproduce this failure is to attempt to checkout a repo other than the one specified by RepositoryName in the bitbucket-pullrequest-builder-plugin configuration. 

Doing something like
git branch: "*/master", credentialsId: '****', url: 'git@bitbucket.org:ACCOUNT/DIFFERENT_REPO.git'
in the jenkins pipeline seems to hit this failure. 
Are you not able to see the failure produced in this way?

**Comment by drew222** [comment]
@CodeMonk I'm sorry I misread the failure when I changed from the checkout gitscm syntax to the git branch: syntax . This fixed the problem, thanks!

**Comment by CodeMonk** [comment]
@drew222 I'm so happy that worked for you! I had no idea how I was going to be able to repro, though, I had not tried a different branch.

But, now that you're working, and the emergency is over, I think there is a bug. I think `checkout scm` should work in a PR build. I was surprised when I saw the different syntax in my pipeline file, that I obviously added years ago to just get my build to work.

I'll add details to the issue here, or a new issue, to try to focus on for our next release ;)

**Comment by drew222** [comment]
So after digging into files in my jenkins workspace I'm seeing that the second repo isn't there. 
While the git branch: doesn't cause a failure, its still doing a rev-parse on the first repos commit and then checking out a revision from the first repo instead of the second.

So my pipeline goes to the next step, but I think there may be a bug even for this syntax still.

Here's my output :
[Pipeline] git
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url git@bitbucket.org:ACCOUNT/REPO2.git # timeout=10
Fetching upstream changes from git@bitbucket.org:ACCOUNT/REPO2.git
 > git --version # timeout=10
using GIT_SSH to set credentials Jenkins SSH Key
 > git fetch --tags --progress git@bitbucket.org:ACCOUNT/REPO2.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse 49efdff6f914^{commit} # timeout=10
 > git branch -a -v --no-abbrev --contains 49efdff6f914e7daa67180e495137faf08ff78db # timeout=10
Checking out Revision 49efdff6f914e7daa67180e495137faf08ff78db (origin/REPO1)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 49efdff6f914e7daa67180e495137faf08ff78db
 > git branch -a -v --no-abbrev # timeout=10
 > git checkout -b master 49efdff6f914e7daa67180e495137faf08ff78db
Commit message: "wip"
 > git rev-list --no-walk 98dda07a24623e12c65b72b674ae058cd0d35b6a # timeout=10


Our builds don't use the bitbucket-pullrequest-builder-plugin yet, so no emergencies over here. Still seems to be an issue with a 2nd repo being pulled down.

**Comment by drew222** [comment]
@CodeMonk After some digging, I found here : https://issues.jenkins-ci.org/browse/JENKINS-26587 that injecting a RevisionParameterAction could cause this behavior.

I think this line may be the cause of the behavior we're seeing? 
https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/blob/master/src/main/java/bitbucketpullrequestbuilder/bitbucketpullrequestbuilder/BitbucketBuildTrigger.java#L217

**Comment by CodeMonk** [comment]
So, if I'm understanding that fix correctly, the issue is that there's a
second url that needs to be used, instead of trying to checkout the hash?
Where would that URL come from?

Kudos on digging so deep toward the issue, but, I'm not sure if there is
anything in the PR builder to fix. Sounds like you need more or better urls
for your second repo? Or am I not understanding your build?

**Comment by drew222** [comment]
The issue is that bitbucket-pullrequest-builder-plugin is injecting a RevisionParameterAction into the jenkins build at line 217 in BitbucketBuildTrigger.java, which affects each git-scm call to download a repo. The first repo my build is trying to download contains the commit that is passed in via the RevisionParameterAction but the second repo doesn't and so it fails to download. 

I found that newer versions of RevisionParameterAction accept a url Argument. The git scm plugin looks at this url field of the RevisionParameterAction and only uses the commit provided if it belongs to the repo at the specified url. If it doesn't exist in a repo that the git scm plugin is attempting to download, it prints "skipping resolution of commit ab813c6b364f, since it originates from another repository" and then proceeds normally. 

I have this fix working locally, I'll throw up a pr tomorrow sometime to show and maybe we can get it in the next release.

**Comment by drew222** [comment]
https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/pull/177

**Comment by DerFlob** [comment]
Hello @CodeMonk

We have enountered this issue in our Pipeline as well. It seems the original fix from #177 didn't make it in the last release of plugin. But you re-implemented the fix in #211. Since you are the maintainer of the offical plugin repo as well, are you to make a new release of the plugin in the forseeable future?

Thank you very much for your work!

**Comment by CodeMonk** [comment]
I tried to push out a release a bit ago, but, I'm having issues with the
travis builds.

I'll try to find some time this week to revisit. (I couldn't even build a
version for myself to sideload. Good times. Java is awesome!)

-Dave

**Comment by indiv0** [comment]
Any updates on this?

**Comment by CodeMonk** [comment]
A new build went out with the fix a week or so ago. Should be version 1.5.0.

Please let me know if the fix works for you.
