### ISSUE TITLE
Pligin takes long time to kick the jenkins job

### ISSUE THREAD

**Issue by chris248570** [nishio-dens/bitbucket-pullrequest-builder-plugin#200]
I tried in different Jenkins and using 1.30.0 plugin..
Always plugin is taking too long to kick my Jenkins build job??...
Is an issue or it's happening only for me..

**Comment by CodeMonk** [comment]
Welp, I'm not sure if anyone can help answer your question, since you're missing a couple of minor details.

1. How slow is it? 1 second? 1 minute? 1 hour? 1 day? 1 year?
2. Since 'kick' is a bit ambiguous, how, EXACTLY, are you `kicking off your Jenkins build job`?

Perhaps if we know what you are doing, and how long it is taking, we can actually comment on whether or not your experience is an issue, or it's happening only for you.

-Dave

**Comment by chris248570** [comment]
@CodeMonk thanks for checking my issue.. 
My Jenkins jobs are taking time delay up to 30 to 40 min after my Pullrequest created/updated.. and sometimes  if PullRequest is updated it's not even triggering the Jenkins job..
And I am seeing Rate limit is exceeded in the Jenkins system logs... 
Fetch PullRequests.
Response status: HTTP/1.1 429 Unknown Status Code URI: https://bitbucket.org/api/..../pullrequests/?pagelen=50
Rate limit for this resource has been exceeded

**Comment by CodeMonk** [comment]
Yup -- there you have it. Atlassian throttles -- a LOT.

Cheers!

**Comment by chris248570** [comment]
@CodeMonk  any thoughts why my jobs are getting delays.. anything in your mind related to this error???

**Comment by CodeMonk** [comment]
Yes. When the code tries to look for new pull requests, the request fails, because it's being throttled by atlassian.

Eventually it will succeed.

If the period of time between the throttling and eventual success is non zero, then that total cumulative period will be delay in kicking off the build.

Once atlassian STARTS throttling, the throttling is generally pretty severe, so, that delay could get quite large.

There are some feature tickets here on moving to a triggered vs polling system, but, no one has contributed code, and I've been swamped lately :(

-Dave

**Comment by chris248570** [comment]
Thanks @CodeMonk .
Is there any alternate way to fix this issue right now by changing any settings or config before the new version or new code fix??..

**Comment by CodeMonk** [comment]
Don't hit bitbucket's api so hard.  If you are using other plugins, try to be nice with them.

For this plugin, change the cron line to not poll as often. Hopefully that will reduce the throttling.

**Comment by reddydheeraj** [comment]
hello @CodeMonk is there any possibility in kicking off the PR build in Jenkins based off the "Webhook to Jenkins for Bitbucket Server" plugin in Bitbucket.. 
![image](https://user-images.githubusercontent.com/51835172/60359295-aac26c00-99a6-11e9-9aa1-f37c16b037e2.png)

If this is possible .. presuming this would avoid polling to Bitbucket and kicks off the PR build without any delays. 
Also last but not least we've restrictions on polling to Bitbucket in our organization. Its a major stumbling block for us to get this amazing plugin into our workplace.

I'm very enthusiastic to know possibilities of avoiding polling (cron) and kickoff the PR build as soon as PR is opened with "Bitbucket Pull Requests Plugin"

**Comment by CodeMonk** [comment]
It is definitely possible -- that's what bbprb does. However, at this time,
this plugin does not support it.

-Dave
