### ISSUE TITLE
Using many jobs to review pull requests

### ISSUE THREAD

**Issue by itayariel** [nishio-dens/bitbucket-pullrequest-builder-plugin#30]
Our automated tests take lots of time. We want Jenkins to run its tests in parallel on our pull requests.
Can we create many jobs that will review pull requests., but only one job will run after every commit or pull request creation?

**Comment by bskart** [comment]
Would really be a great feature, we are running into the problem that we build up big queues, because each time you have N PRs open and merge one, the N-1 still open PRs have to rerun against the changes in the main-branch, and if another gets merged while that is happening, there might be new jobs for each PR in the queue before any of them even got retested.
