### ISSUE TITLE
Does not rebuild if branch updates

### ISSUE THREAD

**Issue by nvartolomei** [nishio-dens/bitbucket-pullrequest-builder-plugin#72]
For some reasons build is not triggered when PR is updated.

Where can I look for logs?

**Comment by maxvodo** [comment]
Logs of plugin available in the `Manage Jenkins > System Log > All Logs` log file. 
Search lines with `bitbucketpullrequestbuilder.bitbucketpullrequestbuilder` template.

Clarify please exactly what you mean: PR updated and jenkins not triggered build (PR already build for this moment)? Or if build has updates plugin not triggered build?

**Comment by maxvodo** [comment]
@nvartolomei, have any news?

**Comment by nvartolomei** [comment]
Can't reproduce it anymore after reconfigured the plugin. I'll re-open this if it will happen again.

**Comment by dimitrez** [comment]
hey guys, i have this same issue in last 3 month. I have Jenkins with Bitbucket Pull Request builder, all was working normally, but in last 3 month i not understanding why - sometimes after we have PR update or new PR plugin not starting build PR, help only restarting Jenkins. I investigate logs but in logs no error,  it feel likes that cron into plugin or Jenkins not working or have broken cache. I not have any idea how i can fix it or what yet investigate.

All other Jenkins tasks working correctlt (other tasks based on BitBucket hooks, Docker hooks, monitoring BitBucket repo chnges for branch.)


This is my currentt plugin config. 

![screen_2018-12-11_12-02-59](https://user-images.githubusercontent.com/19185339/49793126-1c093d00-fd3d-11e8-9b63-be453f043309.png)

I have Jenkins log for `bitbucketpullrequestbuilder.bitbucketpullrequestbuilder` log level `ALL` but in logs no any errors messages. If  need i can add log from Jenkins.

after restarting Jenkins sometimes all working correctly, but then after this problem is repeated.

**Comment by CodeMonk** [comment]
@dimitrez I know the behavior you are talking about. I have seen instances where the PR builder stops creating new builds from comments or even new pushes. Can you please open a new issue with your details, since I doubt this one from two years ago is the same thing. The sporatic behavior started for us a couple of months ago too -- could even coincide with the new update.
