### ISSUE TITLE
Add support for deployment keys.

### ISSUE THREAD

**Issue by schinckel** [nishio-dens/bitbucket-pullrequest-builder-plugin#79]
We use BitBucket deployment keys for read-only access to repositories, and indeed that is how Jenkins pulls from BB for our builds.

I'd like to be able to just use the same mechanism for this plugin.

**Comment by maxvodo** [comment]
Plugin uses BitBucket REST API that provides two ways to auth requests: login+passwd and OAuth consumer key. At this moment plugin using only login+passwd auth.

**Comment by redthor** [comment]
Is there another bitbucket plugin that uses [oauth](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html)? We could re-use the code for this plugin?

It'd be great to generate an oauth key in bitbucket settings and add it to CI instead of creating a dummy user or adding our own credentials to the plugin.

**Comment by driverpt** [comment]
+1 for OAuth Consumer Key

**Comment by maxvodo** [comment]
Hi @driverpt @redthor @schinckel !
Good news: you can try BBPR trigger version with OAuth support [here](https://github.com/maxvodo/bitbucket-pullrequest-builder-plugin/releases/tag/bitbucket-pullrequest-builder-fix-issue-79). 

You may write some feedback to my repo fork directly :) After that I make PR to master repo.

**Comment by driverpt** [comment]
@maxvodo Create a PR to this repository so you can get more testers

**Comment by hugoduraes** [comment]
Hi @maxvodo, have you created a PR on this repository for the OAuth feature?
